# Generated by Django 4.2.7 on 2023-12-04 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                ("user_id", models.TextField(primary_key=True, serialize=False)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("expires_at", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "tokens",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ArtistModel",
            fields=[
                ("artist_id", models.TextField(primary_key=True, serialize=False)),
                ("artist_name", models.TextField(blank=True, null=True)),
                ("artist_genres", models.TextField(blank=True, null=True)),
                ("artist_popularity", models.IntegerField(blank=True, null=True)),
                ("artist_followers", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "artists",
                "ordering": ["-artist_followers"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TrackModel",
            fields=[
                ("track_id", models.TextField(primary_key=True, serialize=False)),
                ("track_name", models.TextField(blank=True, null=True)),
                ("track_album", models.TextField(blank=True, null=True)),
                ("track_duration", models.IntegerField(blank=True, null=True)),
                ("track_popularity", models.IntegerField(blank=True, null=True)),
                ("track_release_date", models.DateField(blank=True, null=True)),
                ("track_explicit", models.BooleanField(blank=True, null=True)),
                ("track_artists", models.ManyToManyField(to="lynify.artistmodel")),
            ],
            options={
                "db_table": "tracks",
                "ordering": ["-track_popularity"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="HistoryModel",
            fields=[
                ("timestamp", models.DateTimeField(primary_key=True, serialize=False)),
                ("track", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="lynify.trackmodel")),
            ],
            options={
                "db_table": "history",
                "ordering": ["-timestamp"],
                "managed": True,
            },
        ),
    ]
